# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaProduto.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_MainWindow(object):
    con=None
    cursor=None

    def conectar(self):
        self.con= mysql.connector.connect(host='localhost', database='loja',
                                          user='root', password='')
        if self.con.is_connected():
            self.cursor=self.con.cursor()
            return True
        return False


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 241)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 47, 14))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 47, 14))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 80, 47, 14))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 110, 47, 14))
        self.label_4.setObjectName("label_4")
        self.leCodigo = QtWidgets.QLineEdit(self.centralwidget)
        self.leCodigo.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.leCodigo.setObjectName("leCodigo")
        self.leDescricao = QtWidgets.QLineEdit(self.centralwidget)
        self.leDescricao.setGeometry(QtCore.QRect(110, 50, 351, 20))
        self.leDescricao.setObjectName("leDescricao")
        self.lePreco = QtWidgets.QLineEdit(self.centralwidget)
        self.lePreco.setGeometry(QtCore.QRect(110, 80, 113, 20))
        self.lePreco.setObjectName("lePreco")
        self.leQtde = QtWidgets.QLineEdit(self.centralwidget)
        self.leQtde.setGeometry(QtCore.QRect(110, 110, 113, 20))
        self.leQtde.setObjectName("leQtde")
        self.pbCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pbCadastrar.setGeometry(QtCore.QRect(40, 150, 75, 23))
        self.pbCadastrar.setObjectName("pbCadastrar")
        self.pbCadastrar.clicked.connect(self.cadastrar)

        self.pbConsultar = QtWidgets.QPushButton(self.centralwidget)
        self.pbConsultar.setGeometry(QtCore.QRect(120, 150, 75, 23))
        self.pbConsultar.setObjectName("pbConsultar")
        self.pbConsultar.clicked.connect(self.consultar)

        self.pbAlterar = QtWidgets.QPushButton(self.centralwidget)
        self.pbAlterar.setGeometry(QtCore.QRect(200, 150, 101, 23))
        self.pbAlterar.setObjectName("pbAlterar")
        self.pbAlterar.clicked.connect(self.alterar)

        self.pbExcluir = QtWidgets.QPushButton(self.centralwidget)
        self.pbExcluir.setGeometry(QtCore.QRect(310, 150, 75, 23))
        self.pbExcluir.setObjectName("pbExcluir")
        self.pbExcluir.clicked.connect(self.excluir)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        if self.conectar():
            print('Conectado ao banco de dados!')
            self.limpar()
        else:
            print('Falha na conexão com o banco de dados!')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Loja de Informática"))
        self.label.setText(_translate("MainWindow", "Código"))
        self.label_2.setText(_translate("MainWindow", "Descrição"))
        self.label_3.setText(_translate("MainWindow", "Preço"))
        self.label_4.setText(_translate("MainWindow", "Qtde"))
        self.pbCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.pbConsultar.setText(_translate("MainWindow", "Consultar"))
        self.pbAlterar.setText(_translate("MainWindow", "Alterar preço"))
        self.pbExcluir.setText(_translate("MainWindow", "Excluir"))

    def cadastrar(self):
        sql='insert into produto values (%s,%s,%s,%s)'
        codigo=int(self.leCodigo.text())
        descricao=self.leDescricao.text()
        preco=float(self.lePreco.text())
        qtde=int(self.leQtde.text())
        values=(codigo, descricao, preco, qtde)
        self.cursor.execute(sql, values)
        if self.cursor.rowcount>0:
            self.con.commit()
            print('Produto cadastrado com sucesso!!')
            self.limpar()
        else:
            print('Falha no cadastro do produto!!')

    def limpar(self):
        self.leCodigo.setText('')
        self.leDescricao.setText('')
        self.lePreco.setText('')
        self.leQtde.setText('')
        self.leCodigo.setFocus()
        self.pbCadastrar.setEnabled(False)
        self.pbAlterar.setEnabled(False)
        self.pbExcluir.setEnabled(False)

    def consultar(self):
        sql='select * from produto where codigo='+self.leCodigo.text()
        self.cursor.execute(sql)
        dados=self.cursor.fetchone()
        if dados!=None:
            self.leDescricao.setText(dados[1])
            self.lePreco.setText(str(dados[2]))
            self.leQtde.setText(str(dados[3]))
            self.pbAlterar.setEnabled(True)
            self.pbExcluir.setEnabled(True)
            self.pbCadastrar.setEnabled(False)
        else:
            self.leDescricao.setText('')
            self.lePreco.setText('')
            self.leQtde.setText('')
            self.pbAlterar.setEnabled(False)
            self.pbExcluir.setEnabled(False)
            self.pbCadastrar.setEnabled(True)

    def alterar(self):
        codigo=int(self.leCodigo.text())
        preco=float(self.lePreco.text())
        sql='update produto set preco=%s where codigo=%s'
        dados=(preco, codigo)
        self.cursor.execute(sql, dados)
        if self.cursor.rowcount>0:
            print('Preço atualizado com sucesso!')
            self.con.commit()
            self.limpar()

    def excluir(self):
        sql='delete from produto where codigo='+self.leCodigo.text()
        self.cursor.execute(sql)
        if self.cursor.rowcount>0:
            print('Produto excluído!')
            self.con.commit()
            self.limpar()

# ---- INICIO DO PROGRAMA
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
