SELECT WORKDEPT, LASTNAME, SALARY+COMM+BONUS, INCOME,
coalesce(SALARY+COMM+BONUS, 0) 'INCOME'
FROM EMPLOYEE
WHERE WORKDEPT LIKE "D11" AND 
coalesce(SALARY+COMM+BONUS, 0)>(SALARY+(SALARY*0.1))
ORDER BY INCOME DESC;