SELECT DEPTNO, DEPTNAME
FROM DEPARTMENT
WHERE DEPTNO LIKE '_1_'
ORDER BY DEPTNO;

SELECT DEPTNO, DEPTNAME
FROM DEPARTMENT
WHERE DEPTNO LIKE '_1%'
ORDER BY DEPTNO;

SELECT DEPTNO, DEPTNAME
FROM DEPARTMENT
WHERE DEPTNO LIKE '%1_'
ORDER BY DEPTNO;
