SELECT PROJNO, ACTNO, EMSTDATE, EMENDATE
FROM EMP_ACT
WHERE PROJNO LIKE 'AD%'
AND (ACTNO = 10 OR ACTNO = 80 OR ACTNO = 180)
ORDER BY PROJNO, ACTNO;


SELECT PROJNO, ACTNO, EMSTDATE, EMENDATE
FROM EMP_ACT
WHERE PROJNO LIKE 'AD%' AND ACTNO IN(10, 80, 180)
ORDER BY PROJNO, ACTNO;