SELECT EMPNO, LASTNAME, SALARY, BONUS
FROM EMPLOYEE
WHERE (BONUS >= 800 AND BONUS <= 1000)
ORDER BY BONUS;


SELECT EMPNO, LASTNAME, SALARY, BONUS
FROM EMPLOYEE
WHERE BONUS BETWEEN 800 AND 1000
ORDER BY BONUS;